[package]
name = "visuarust-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
log.workspace = true
polonius-engine.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
