[package]
name = "rustowl"
version = "0.1.0"
edition = "2021"
default-run = "cargo-owl"

[workspace]
members = ["rustowl-core"]
[workspace.dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.135"
log = "0.4.22"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros", "sync"] }

[dependencies]
rustowl-core = { path = "./rustowl-core" }
serde.workspace = true
serde_json.workspace = true
log.workspace = true
simple_logger = { version = "5.0.0", features = ["stderr"] }
tokio.workspace = true

[[bin]]
name = "cargo-owl"
path = "src/main.rs"

[[bin]]
name = "rustowlc"
path = "src/owlc.rs"
