name: Build RustOwl

on:
  push:

jobs:
  rustowl:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup install
        working-directory: rustowl
      - name: Build
        run: cargo build --release
        working-directory: rustowl

      - name: Set host tuple to env
        run: echo "host_tuple=$(rustc --print=host-tuple)" >> $GITHUB_ENV
        working-directory: rustowl
      - name: Rename artifacts
        shell: bash
        run: |
          mkdir -p bin
          for f in $(find rustowl/target/release -maxdepth 1 -perm -111 -type f); do
            BASENAME="$(basename "$f")"
            NAME="${BASENAME%%.*}";
            mv "$f" "bin/$NAME-${{ env.host_tuple }}";
          done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rustowl-${{ env.host_tuple }}
          path: bin/*
