name: Release RustOwl

on:
  push:
    tags:
      - v*

jobs:
  extension:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --frozen-locked
        working-directory: ./vscode
      - name: Create VSIX
        run: yes | yarn build
        working-directory: ./vscode
      - name: Create rustowl zip
        run: zip -r rustowl.zip ./rustowl
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: auto RustOwl update
          files: |
            ./vscode/**/*.vsix
            ./rustowl.zip
            ./rustowl/install.sh
          draft: true
