name: Release RustOwl

on:
  push:
    tags:
      - v*

jobs:
  rustowl:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15
          - windows-2022
          - windows-11-arm

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
        working-directory: rustowl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # We don't have rustup on the Windows 11 Arm64 runner yet, so manually installing it.
      - if: ${{ matrix.os == 'windows-11-arm' }}
        name: Install rustup
        run: |
          URL='https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe'
          HASH="$(curl -sSL "${URL}.sha256")"
          curl -sSL -o ./rustup-init.exe "${URL}"
          if [ "$(sha256sum ./rustup-init.exe | cut -d' ' -f 1)" = "${HASH}" ]; then
            ./rustup-init.exe -y --no-update-default-toolchain
            echo "${USERPROFILE}\.cargo\bin" >> "${GITHUB_PATH}"
          else
            echo "::error::The SHA256 digest does not match."
            exit 1
          fi

      - name: Setup Rust
        run: rustup install
      - name: Build
        run: cargo build --release

      - name: check host tuple
        run: |
          echo "host_tuple=$(rustc --print=host-tuple)" >> $GITHUB_ENV
          ([[ "$(rustc --print=host-tuple)" == *msvc* ]] && echo "exec_ext=.exe" || echo "exec_ext=") >> $GITHUB_ENV
      - name: Set runtime tarball name
        run: echo "tarball_name=runtime-${{ env.host_tuple }}.tar.gz" >> $GITHUB_ENV

      - name: Setup tarball artifacts
        run: |
          rm -rf runtime
          cp -r "$(rustc --print=sysroot)" runtime

          cp target/release/rustowl${{ env.exec_ext }} ./runtime
          cp target/release/rustowlc${{ env.exec_ext }} ./runtime

          cp ../README.md ./runtime
          cp ../LICENSE ./runtime

          rm -rf ${{ env.tarball_name }}
          cd runtime;
          ls | \
            xargs -I % find % -type f | \
            grep -E '\.(rlib|so|dylib|dll)$' | \
            xargs tar -czvf ../${{ env.tarball_name }} README.md LICENSE rustowl${{ env.exec_ext }} rustowlc${{ env.exec_ext }}

          cp ./rustowl${{ env.exec_ext }} ../rustowl-${{ env.host_tuple }}${{ env.exec_ext }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rustowl-runtime-${{ env.host_tuple }}
          path: |
            rustowl/rustowl-${{ env.host_tuple }}${{ env.exec_ext }}
            rustowl/${{ env.tarball_name }}


  vscode:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --frozen-locked
        working-directory: ./vscode
      - name: Create VSIX
        run: yarn build
        working-directory: ./vscode

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rustowl-vscode
          path: vscode/**/*.vsix


  release:
    runs-on: ubuntu-latest
    needs:
      - rustowl
      - vscode
    permissions:
      contents: write

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: rustowl-*
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: auto RustOwl update
          files: artifacts/**/*
          draft: true
